### ISSUE TITLE
Number 9 is redundant

### ISSUE THREAD

**Issue by dyegolara** [Widdershin/programmers-oath#57] opened 2018-02-27 23:44 UTC
I think number 9 is a bit redundant considering numbers 3 and 5 express the same idea, even, maybe also number 1:

`1. I will respect the learnings of those programmers who came before me, and share my learnings with those to come.`

`3. I will not be ashamed to say "I don't know", and I will ask for help when I am stuck.`

`5. I will tread most carefully in matters of life or death. I will be humble and recognize that I will make mistakes.`

`9. I will recognize that I can and will be wrong. I will keep an open mind, and listen to others carefully and with respect.`

I suggest drop that number or maybe clarify the difference with the mentioned ones

**Comment by mo-g** [comment] 2018-02-28 00:10
This is pretty much a duplicate of #37, which I'm also in favor of.

You have different ideas for the solutions though. Care to weight in on #40 as well?

**Closed by mo-g** 2018-02-28 00:10 UTC
Labels: duplicate

**Comment by mo-g** [comment] 2018-02-28 00:11
(Also, if you feel I was hasty with the close, I'm happy to reopen and discuss.) :)
